import { GalleryImageProps } from '../../components/ImageGallery/GalleryImageDetails';
import { VideoItemProps } from '../../components/VideoCollection/VideoCollection';
import { FacilityItem } from '../../views/facility/ItemModal';

export const AnnData = [
  {
    id: '1',
    selected: false,
    numbering: 1,
    title: '공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사',
    author: '관리자 1',
    date: '2023-05-05',
    body: '글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기.',
  },
  { id: '2', selected: false, numbering: 2, title: 'Short', author: '관리자 2', date: '2023-05-05', body: '' },
  { id: '3', selected: false, numbering: 3, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '4', selected: false, numbering: 4, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '5', selected: false, numbering: 5, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '6', selected: false, numbering: 6, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '7', selected: false, numbering: 7, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '8', selected: false, numbering: 8, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '9', selected: false, numbering: 9, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '10', selected: false, numbering: 10, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '11', selected: false, numbering: 11, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '12', selected: false, numbering: 12, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
];

export const BoardData = [
  {
    id: '1',
    selected: false,
    numbering: 1,
    title: '공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사',
    author: '관리자 1',
    date: '2023-05-05',
    body: '글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기.',
  },
  { id: '2', selected: false, numbering: 2, title: 'Short', author: '관리자 2', date: '2023-05-05', body: '' },
  { id: '3', selected: false, numbering: 3, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '4', selected: false, numbering: 4, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '5', selected: false, numbering: 5, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '6', selected: false, numbering: 6, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '7', selected: false, numbering: 7, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '8', selected: false, numbering: 8, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '9', selected: false, numbering: 9, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '10', selected: false, numbering: 10, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '11', selected: false, numbering: 11, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '12', selected: false, numbering: 12, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
];

export const VideoCollectionData: VideoItemProps[] = [
  {
    id: '1',
    selected: false,
    numbering: 1,
    image: '/logo192.png',
    title: '전영은 콘텐츠 테스트 전영은 콘텐츠 테스트 전영은 콘텐츠 테스트 전영은 콘텐츠 테스트 전영 츠 테스트 전영ㅇ',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '2',
    selected: false,
    numbering: 2,
    video_id: 'jNQXAC9IVRw',
    image: '/logo192.png',
    title: 'Video 2',
    description:
      '튼튼하며, 천지는 곳이 광야에서 천하를 말이다. 불러 청춘의 바이며, 있는 못할 석가는 끓는 생의 찾아다녀도, 사막이다. 크고 두손을 원대하고, 인간의 봄바람이다. 이성은 넣는 만천하의 불어 구하지 우는 끓는 것이다. 끓는 천지는 안고, 그들은 위하여 인생을 들어 무엇이 희망의 있는가? 투명하되 가는 따뜻한 않는 생명을 아니다. 우리의 영원히 자신과 그러므로 무엇이 피가 희망의 교향악이다.튼튼하며, 천지는 곳이 광야에서 천하를 말이다. 불러 청춘의 바이며, 있는 못할 석가는 끓는 생의 찾아다녀도, 사막이다. 크고 두손을 원대하고, 인간의 봄바람이다. 이성은 넣는 만천하의 불어 구하지 우는 끓는 것이다. 끓는 천지는 안고, 그들은 위하여 인생을 들어 무엇이 희망의 있는가? 투명하되 가는 따뜻한 않는 생명을 아니다. 우리의 영원히 자신과 그러므로 무엇이 피가 희망의 교향악이다.',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '3',
    selected: false,
    numbering: 3,
    image: '/logo192.png',
    title: 'Video 3',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '4',
    selected: false,
    numbering: 4,
    image: '/logo192.png',
    title: 'Video 4',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '5',
    selected: false,
    numbering: 5,
    image: '/logo192.png',
    title: 'Video 5',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '6',
    selected: false,
    numbering: 6,
    image: '/logo192.png',
    title: 'Video 6',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '7',
    selected: false,
    numbering: 7,
    image: '/logo192.png',
    title: 'Video 7',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '8',
    selected: false,
    numbering: 8,
    image: '/logo192.png',
    title: 'Video 8',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '9',
    selected: false,
    numbering: 9,
    image: '/logo192.png',
    title: 'Video 9',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '10',
    selected: false,
    numbering: 10,
    video_id: 'jNQXAC9IVRw',
    image: '/logo192.png',
    title: 'Video 10',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '11',
    selected: false,
    numbering: 11,
    video_id: 'jNQXAC9IVRw',
    image: '/logo192.png',
    title: 'Video 11',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '12',
    selected: false,
    numbering: 12,
    video_id: 'jNQXAC9IVRw',
    image: '/logo192.png',
    title: 'Video 12',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
  {
    id: '13',
    selected: false,
    numbering: 13,
    video_id: 'jNQXAC9IVRw',
    image: '/logo192.png',
    title: 'Video 13',
    description: 'acb3213123555dsadsad',
    author: 'admin',
    date: '2023-10-16',
  },
];

export const FacilityData: FacilityItem[] = [
  {
    numbering: 1,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/logo192.png',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
    details: [
      { date: '2022.03.22', hour: 4, amount: 3, effort: 12 },
      { date: '2022.05.20', hour: 3, amount: 2, effort: 15 },
      { date: '2022.03.22', hour: 5, amount: 5, effort: 10 },
      { date: '2022.03.22', hour: 5, amount: 5, effort: 10 },
    ],
  },
  {
    numbering: 2,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/ctest.jpg',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 3,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/logo192.png',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 4,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/logo192.png',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 5,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/logo192.png',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 6,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: 'item1.jpg',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 7,
    district: '기장군',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/logo192.png',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 8,
    district: '기장군',
    title: '부산국립해양대학교 진입로 방파재',
    img: 'item1.jpg',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
];

export const LabData = [
  {
    id: '1',
    selected: false,
    numbering: 1,
    title: '공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사',
    author: '관리자 1',
    date: '2023-05-05',
    body: '글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기.',
  },
  { id: '2', selected: false, numbering: 2, title: 'Short', author: '관리자 2', date: '2023-05-05', body: '' },
  { id: '3', selected: false, numbering: 3, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '4', selected: false, numbering: 4, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '5', selected: false, numbering: 5, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '6', selected: false, numbering: 6, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '7', selected: false, numbering: 7, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '8', selected: false, numbering: 8, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '9', selected: false, numbering: 9, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '10', selected: false, numbering: 10, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '11', selected: false, numbering: 11, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '12', selected: false, numbering: 12, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
];

export const UserManagementData = [
  {
    id: '1',
    selected: false,
    name: '홍길동',
    numbering: 1,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '2',
    selected: false,
    name: '홍길동',
    numbering: 2,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '3',
    selected: false,
    name: '홍길동',
    numbering: 3,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '4',
    selected: false,
    name: '홍길동',
    numbering: 4,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '5',
    selected: false,
    name: '홍길동',
    numbering: 5,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '6',
    selected: false,
    name: '홍길동',
    numbering: 6,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '7',
    selected: false,
    name: '홍길동',
    numbering: 7,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '8',
    selected: false,
    name: '홍길동',
    numbering: 8,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '9',
    selected: false,
    name: '홍길동',
    numbering: 9,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '10',
    selected: false,
    name: '홍길동',
    numbering: 10,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '11',
    selected: false,
    name: '홍길동',
    numbering: 11,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '12',
    selected: false,
    name: '홍길동',
    numbering: 12,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
];
