version: "3"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5445:5432
    expose:
      - 5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4044:4044
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
